package com.github.sirjacob.sahs_membership.old;

import com.github.sirjacob.sahs_membership.TrayIcon;
import java.awt.AWTException;
import java.awt.SystemTray;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author SirJacob <https://github.com/SirJacob>
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
        //Check the SystemTray is supported
        if (!SystemTray.isSupported()) {
            System.out.println("SystemTray is not supported.");
            return;
        }
        try {
            java.awt.TrayIcon trayIcon = new java.awt.TrayIcon(new ImageIcon(getClass().getResource("/icon.png")).getImage());
            trayIcon.setImageAutoSize(true);
            trayIcon.setToolTip("SAHS Membership DB Updater");
            trayIcon.setPopupMenu(popupMenu);
            SystemTray.getSystemTray().add(trayIcon);
        } catch (AWTException ex) {
            Logger.getLogger(TrayIcon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu = new javax.swing.JPopupMenu();
        menuItemExit = new javax.swing.JMenuItem();

        menuItemExit.setLabel("Exit");
        menuItemExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItemExitMouseClicked(evt);
            }
        });
        popupMenu.add(menuItemExit);
        menuItemExit.getAccessibleContext().setAccessibleName("menuItemExit");

        setMaximumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_menuItemExitMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JPopupMenu popupMenu;
    // End of variables declaration//GEN-END:variables
}
